import "@/css/main.css";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Deep Learning",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh-CN">
      <body className="antialiased text-slate-600 dark:text-slate-300 bg-white dark:bg-slate-900">
        {children}
      </body>
    </html>
  );
}
